### ISSUE TITLE
manage.py won't work help me plz.

### ISSUE THREAD

**Issue by Iderbat** [UniversitaDellaCalabria/django-freeradius-manager#1]
./manage.py
Traceback (most recent call last):
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'identita_digitale'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/idree/django-freeradius-manager/env/lib/python3.8/site-packages/django/apps/config.py", line 246, in create
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Cannot import 'identita_digitale'. Check that 'identity.apps.IdentitaDigitaleConfig.name' is correct.

**Comment by peppelinux** [comment]
Thank you for this issue, I made a commit  to fix this
let me know for any other issues and questions

**Comment by Iderbat** [comment]
thank you, its solved.
